# Generated by Django 4.1.7 on 2023-03-07 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomobilioModelis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marke', models.CharField(max_length=100, verbose_name='Markė')),
                ('modelis', models.CharField(max_length=100, verbose_name='Modelis')),
                ('metai', models.CharField(max_length=4, verbose_name='Pagaminimo metai')),
                ('variklis', models.CharField(max_length=10, verbose_name='Variklis')),
            ],
        ),
        migrations.CreateModel(
            name='Automobilis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valstybinis_nr', models.CharField(max_length=7, verbose_name='Valstybinis Nr.')),
                ('vin_kodas', models.CharField(max_length=20, verbose_name='VIN kodas')),
                ('klientas', models.CharField(max_length=20, verbose_name='Klientas')),
                ('automobilio_modelis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.automobiliomodelis')),
            ],
        ),
        migrations.CreateModel(
            name='Paslauga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(help_text='Įveskite paslaugos pavadinimą (pvz. Alyvos keitimas)', max_length=100, verbose_name='Pavadinimas')),
                ('paslaugos_kaina', models.FloatField(verbose_name='Kaina')),
            ],
        ),
        migrations.CreateModel(
            name='Uzsakymas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Užsakymo data')),
                ('suma', models.FloatField(verbose_name='Suma')),
                ('automobilis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.automobilis')),
            ],
        ),
        migrations.CreateModel(
            name='UzsakymoEilute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiekis', models.IntegerField(verbose_name='Kiekis')),
                ('kaina', models.FloatField(verbose_name='Kaina')),
                ('paslauga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.paslauga')),
                ('uzsakymas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.uzsakymas')),
            ],
        ),
    ]
