# Generated by Django 4.1.7 on 2023-03-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzsakymoeilute',
            name='kaina',
        ),
        migrations.AlterField(
            model_name='uzsakymas',
            name='suma',
            field=models.FloatField(null=True, verbose_name='Suma'),
        ),
    ]
