# Generated by Django 4.1.7 on 2023-03-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_uzsakymas_suma'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzsakymoeilute',
            name='kaina',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
