# Generated by Django 4.1.7 on 2023-03-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_uzsakymoeilute_kaina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzsakymoeilute',
            name='kaina',
            field=models.FloatField(blank=True, null=True, verbose_name='Kaina'),
        ),
    ]
