# Generated by Django 4.1.7 on 2023-03-07 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_paslauga_paslaugos_kaina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzsakymas',
            name='automobilis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.automobilis'),
        ),
        migrations.AlterField(
            model_name='uzsakymoeilute',
            name='paslauga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.paslauga'),
        ),
    ]
