# Generated by Django 4.1.7 on 2023-03-08 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_uzsakymas_automobilis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzsakymoeilute',
            name='paslauga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.paslauga'),
        ),
        migrations.AlterField(
            model_name='uzsakymoeilute',
            name='uzsakymas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.uzsakymas'),
        ),
    ]
