# Generated by Django 4.1.7 on 2023-03-08 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_alter_uzsakymoeilute_paslauga_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzsakymoeilute',
            name='kaina',
        ),
    ]
