# Generated by Django 4.1.7 on 2023-03-08 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_remove_uzsakymas_suma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automobiliomodelis',
            options={'verbose_name': 'Automobilio modelis', 'verbose_name_plural': 'Automobilio modeliai'},
        ),
        migrations.AlterModelOptions(
            name='automobilis',
            options={'verbose_name': 'Automobilis', 'verbose_name_plural': 'Automobiliai'},
        ),
        migrations.AlterModelOptions(
            name='paslauga',
            options={'verbose_name': 'Paslauga', 'verbose_name_plural': 'Padlaugos'},
        ),
        migrations.AlterModelOptions(
            name='uzsakymas',
            options={'verbose_name': 'Užsakymas', 'verbose_name_plural': 'Užsakymai'},
        ),
        migrations.AlterModelOptions(
            name='uzsakymoeilute',
            options={'verbose_name': 'Užsakymo eilutė', 'verbose_name_plural': 'Užsakymo eilutės'},
        ),
        migrations.AlterField(
            model_name='uzsakymoeilute',
            name='uzsakymas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uzsakymo_eilutes', to='service.uzsakymas'),
        ),
    ]
