# Generated by Django 4.1.7 on 2023-03-08 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_alter_automobiliomodelis_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paslauga',
            options={'verbose_name': 'Paslauga', 'verbose_name_plural': 'Paslaugos'},
        ),
    ]
