# Generated by Django 4.1.7 on 2023-03-08 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_alter_paslauga_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzsakymas',
            name='automobilis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.automobilis'),
        ),
        migrations.AlterField(
            model_name='uzsakymoeilute',
            name='uzsakymas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uzsakymo_eilutes', to='service.uzsakymas'),
        ),
    ]
