# Generated by Django 4.1.7 on 2023-03-08 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_alter_uzsakymas_automobilis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilis',
            name='automobilio_modelis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.automobiliomodelis', verbose_name='Automobilis'),
        ),
    ]
