# Generated by Django 4.1.7 on 2023-03-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_alter_automobilis_automobilio_modelis'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzsakymas',
            name='suma',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Suma'),
        ),
        migrations.AddField(
            model_name='uzsakymoeilute',
            name='kaina',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
    ]
