# Generated by Django 4.1.7 on 2023-03-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_uzsakymas_suma_uzsakymoeilute_kaina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paslauga',
            name='paslaugos_kaina',
            field=models.FloatField(help_text='Įveskite paslaugos kainą', max_length=10, verbose_name='Kaina'),
        ),
        migrations.AlterField(
            model_name='uzsakymas',
            name='suma',
            field=models.FloatField(default=0, max_length=10, null=True, verbose_name='Suma'),
        ),
        migrations.AlterField(
            model_name='uzsakymoeilute',
            name='kaina',
            field=models.FloatField(default=0, max_length=10, null=True, verbose_name='Kaina'),
        ),
    ]
