# Generated by Django 4.1.7 on 2023-03-08 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_alter_paslauga_paslaugos_kaina_alter_uzsakymas_suma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzsakymas',
            name='suma',
        ),
        migrations.RemoveField(
            model_name='uzsakymoeilute',
            name='kaina',
        ),
    ]
