# Generated by Django 4.1.7 on 2023-03-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_remove_uzsakymas_suma_remove_uzsakymoeilute_kaina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paslauga',
            name='paslaugos_kaina',
            field=models.DecimalField(decimal_places=2, help_text='Įveskite paslaugos kainą', max_digits=12, verbose_name='Kaina'),
        ),
    ]
