# Generated by Django 4.1.7 on 2023-03-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_alter_paslauga_paslaugos_kaina'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzsakymas',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Patvirtintas'), ('v', 'Vykdomas'), ('i', 'Įvykdytas'), ('a', 'atmestas')], default='p', help_text='Statusas', max_length=1),
        ),
    ]
