# Generated by Django 4.1.7 on 2023-03-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_uzsakymas_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilis',
            name='aprasymas',
            field=models.TextField(default='', max_length=2000, verbose_name='Problemos aprašymas'),
        ),
        migrations.AlterField(
            model_name='uzsakymas',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Patvirtintas'), ('v', 'Vykdomas'), ('i', 'Įvykdytas'), ('a', 'Atmestas')], default='p', help_text='Statusas', max_length=1),
        ),
    ]
