# Generated by Django 4.1.7 on 2023-03-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_automobilis_aprasymas_alter_uzsakymas_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilis',
            name='aprasymas',
        ),
        migrations.AddField(
            model_name='uzsakymas',
            name='aprasymas',
            field=models.TextField(default='', max_length=2000, verbose_name='Problemos aprašymas'),
        ),
    ]
