# Generated by Django 4.1.7 on 2023-03-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_remove_automobilis_aprasymas_uzsakymas_aprasymas'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilis',
            name='cover',
            field=models.ImageField(null=True, upload_to='automobiliai', verbose_name='Nuotrauka'),
        ),
    ]
