# Generated by Django 4.1.7 on 2023-03-15 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0023_automobilis_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzsakymas',
            name='terminas',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Terminas'),
        ),
        migrations.AddField(
            model_name='uzsakymas',
            name='uzsakovas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
