# Generated by Django 4.1.7 on 2023-03-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_uzsakymas_terminas_uzsakymas_uzsakovas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzsakymas',
            name='terminas',
            field=models.DateField(blank=True, null=True, verbose_name='Terminas'),
        ),
    ]
