# Generated by Django 4.1.7 on 2023-03-15 10:29

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0027_automobilis_aprasymas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzsakymas',
            name='aprasymas',
            field=tinymce.models.HTMLField(default='', verbose_name='Problemos aprašymas'),
        ),
    ]
