# Generated by Django 4.1.7 on 2023-03-16 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0028_alter_uzsakymas_aprasymas'),
    ]

    operations = [
        migrations.CreateModel(
            name='UzsakymuAtsiliepimai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sukurimo_data', models.DateTimeField(auto_now_add=True)),
                ('atsiliepimas', models.TextField(max_length=2000, verbose_name='Atsiliepimas')),
                ('komentatorius', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('uzsakymas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.uzsakymas')),
            ],
            options={
                'verbose_name': 'Atsiliepimas',
                'verbose_name_plural': 'Atsiliepimai',
                'ordering': ['-sukurimo_data'],
            },
        ),
    ]
