# Generated by Django 4.1.7 on 2023-03-17 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0030_profilis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilis',
            options={'verbose_name': 'Profilis', 'verbose_name_plural': 'Profiliai'},
        ),
    ]
