# Generated by Django 4.1.7 on 2023-03-21 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0031_alter_profilis_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automobiliomodelis',
            options={'verbose_name': 'Car model', 'verbose_name_plural': 'Car models'},
        ),
        migrations.AlterModelOptions(
            name='automobilis',
            options={'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.AlterModelOptions(
            name='paslauga',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='profilis',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='uzsakymas',
            options={'ordering': ['-data'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='uzsakymoeilute',
            options={'verbose_name': 'Orderline', 'verbose_name_plural': 'Orderlines'},
        ),
        migrations.AlterModelOptions(
            name='uzsakymuatsiliepimai',
            options={'ordering': ['-sukurimo_data'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterField(
            model_name='automobiliomodelis',
            name='marke',
            field=models.CharField(max_length=100, verbose_name='Make'),
        ),
        migrations.AlterField(
            model_name='automobiliomodelis',
            name='metai',
            field=models.CharField(max_length=4, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='automobiliomodelis',
            name='modelis',
            field=models.CharField(max_length=100, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='automobiliomodelis',
            name='variklis',
            field=models.CharField(max_length=10, verbose_name='Engine'),
        ),
        migrations.AlterField(
            model_name='automobilis',
            name='aprasymas',
            field=tinymce.models.HTMLField(default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='automobilis',
            name='cover',
            field=models.ImageField(null=True, upload_to='automobiliai', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='automobilis',
            name='klientas',
            field=models.CharField(max_length=20, verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='automobilis',
            name='valstybinis_nr',
            field=models.CharField(max_length=7, verbose_name='License Plate'),
        ),
        migrations.AlterField(
            model_name='automobilis',
            name='vin_kodas',
            field=models.CharField(max_length=20, verbose_name='VIN code'),
        ),
        migrations.AlterField(
            model_name='paslauga',
            name='paslaugos_kaina',
            field=models.DecimalField(decimal_places=2, help_text='Enter the price of the service', max_digits=12, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='paslauga',
            name='pavadinimas',
            field=models.CharField(help_text='Enter the name of the service (eg oil change)', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='profilis',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='uzsakymas',
            name='aprasymas',
            field=tinymce.models.HTMLField(default='', verbose_name='Description of the problem'),
        ),
        migrations.AlterField(
            model_name='uzsakymas',
            name='automobilis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.automobilis', verbose_name='Vehicle'),
        ),
        migrations.AlterField(
            model_name='uzsakymas',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='uzsakymas',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Confirmed'), ('v', 'In Progress'), ('i', 'Done'), ('a', 'Canceled')], default='p', help_text='Status', max_length=1),
        ),
        migrations.AlterField(
            model_name='uzsakymas',
            name='terminas',
            field=models.DateField(blank=True, null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='uzsakymas',
            name='vartotojas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='uzsakymoeilute',
            name='kiekis',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='uzsakymoeilute',
            name='paslauga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.paslauga', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='uzsakymoeilute',
            name='uzsakymas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uzsakymo_eilutes', to='service.uzsakymas', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='uzsakymuatsiliepimai',
            name='atsiliepimas',
            field=models.TextField(max_length=2000, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='uzsakymuatsiliepimai',
            name='komentatorius',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Commentator'),
        ),
        migrations.AlterField(
            model_name='uzsakymuatsiliepimai',
            name='uzsakymas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.uzsakymas', verbose_name='Order'),
        ),
    ]
