# Generated by Django 4.1.7 on 2023-03-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0032_alter_automobiliomodelis_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paslauga',
            name='pavadinimas',
            field=models.CharField(help_text='Enter the name of the service (eg oil change)', max_length=100, verbose_name='cdName'),
        ),
    ]
